# Generated by Django 4.2.23 on 2025-07-10 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memories.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gif', 'GIF'), ('audio', 'Audio')], default='image', max_length=10)),
                ('media_file', models.FileField(upload_to=memories.models.slide_media_upload_path)),
                ('caption', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='memories.memoryslideshow')),
            ],
        ),
    ]
