# Generated by Django 4.2.23 on 2025-07-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoryslideshow',
            name='uuid',
        ),
        migrations.AddField(
            model_name='memoryslideshow',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
