# Generated by Django 4.2.23 on 2025-07-12 01:32

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_remove_memoryslideshow_uuid_memoryslideshow_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryslideshow',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to=memories.models.slide_media_upload_path),
        ),
    ]
