# Generated by Django 4.2.23 on 2025-07-12 15:21

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_memoryslideshow_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='media_file',
            field=models.FileField(blank=True, upload_to=memories.models.slide_media_upload_path),
        ),
    ]
