# Generated by Django 4.2.23 on 2025-07-19 03:12

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_alter_slide_media_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='memoryslideshow',
            name='description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memoryslideshow',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='slide',
            name='caption_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='media_file',
            field=models.FileField(blank=True, upload_to=memories.models.slide_media_upload_path_not_profile),
        ),
    ]
