# Generated by Django 4.2.23 on 2025-07-19 04:09

from django.db import migrations, models
import memories.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_alter_slide_options_memoryslideshow_description_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryslideshow',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to=memories.models.slide_media_upload_path),
        ),
    ]
