# Generated by Django 4.2.23 on 2025-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_memoryslideshow_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryslideshow',
            name='profile_theme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memoryslideshow',
            name='slide_theme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
