# Generated by Django 4.2.23 on 2026-01-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0009_add_elegant_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryslideshow',
            name='profile_theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('elegant', 'Classic & Elegant'), ('serene', 'Nature-Inspired & Serene')], default='modern', help_text='Select the theme for the profile page', max_length=20),
        ),
        migrations.AlterField(
            model_name='memoryslideshow',
            name='slide_theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('elegant', 'Classic & Elegant'), ('serene', 'Nature-Inspired & Serene')], default='modern', help_text='Select the theme for the slideshow page', max_length=20),
        ),
    ]
