# Generated by Django 4.2.23 on 2026-01-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0010_add_serene_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryslideshow',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of visits to this slideshow'),
        ),
    ]
